In [2]:
import pandas as pd
import os

# Tablas Union

In [11]:
# Cargamos los datasets
#df_propio =pd.read_csv('Tabla_comparativa_MAE_(GridconCCR)(v2).csv')
df_propio=pd.read_excel('Metrics_2R_std_.xlsx', sheet_name='AMAE')

df_review =pd.read_csv('./Review/Ordinal/Resumen/MZE_review.csv')
#le cambiamos el nombre a la columna Dataset
df_review.rename(columns={'Dataset':'dataset'}, inplace=True)

# Unimos los df que comparten la columna dataset
df = pd.merge(df_propio, df_review, on='dataset', how='inner')
df
list_datasets = df['dataset'].tolist()

In [10]:
#seleccionamos las columnas que nos interesan
df2 = df[['dataset','logisticat','logisticat_desb_v2','logisticit','logisticit_desb_v2','logisticregressor','POM','SVORIMLin']].round(3)
df2

,dataset,logisticat,logisticat_desb_v2,logisticit,logisticit_desb_v2,logisticregressor,POM,SVORIMLin
0,ERA,0.732,0.746,0.895,0.895,0.791,0.744,0.759
1,ESL,0.291,0.457,0.297,0.473,0.348,0.295,0.291
2,LEV,0.381,0.563,0.389,0.709,0.492,0.377,0.391
3,SWD,0.429,0.600,0.475,0.765,0.490,0.432,0.431
4,automobile,0.512,0.542,0.542,0.578,0.498,0.533,0.408
5,balance-scale,0.116,0.094,0.143,0.094,0.094,0.094,0.094
6,car,0.079,0.077,0.081,0.077,0.067,0.843,0.080
7,contact-lenses,0.339,0.300,0.394,0.278,0.244,0.383,0.367
8,eucalyptus,0.679,0.678,0.659,0.667,0.669,0.851,0.356
9,newthyroid,0.032,0.036,0.032,0.036,0.025,0.028,0.031
10,pasture,0.430,0.411,0.389,0.404,0.422,0.504,0.344
11,squash-stored,0.408,0.456,0.397,0.459,0.438,0.618,0.372
12,squash-unstored,0.246,0.274,0.241,0.262,0.262,0.651,0.315
13,tae,0.539,0.539,0.503,0.497,0.474,0.496,0.476
14,toy,0.705,0.797,0.860,0.848,0.757,0.711,0.736
15,winequality-red,0.406,0.840,0.402,0.916,0.584,0.403,0.411

In [11]:
# Guardamos el df
df2.to_csv('0.Comparativa_MZE_Propio+Review.csv', index=False)

In [36]:
# Pasamos el df a codigo latex
print(df.to_latex(index=False))

\begin{tabular}{lrrrrrrrrrrrrrrrrrrrrr}
\toprule
dataset & logisticat & logisticat_desb_v2 & logisticit & logisticit_desb_v2 & logisticregressor & NNOP & GPOR & NNPOM & REDSVM & ELMOP & POM & SVOREX & SVMOP & ORBALL & SVORIM & KDLOR & SVR & CSSVC & SVORIMLin & SCV1V1 & SVC1VA \\
\midrule
ERA & 1.223333 & 1.442400 & 2.790000 & 2.815600 & 1.734533 & 1.178711 & 1.241333 & 1.259333 & 1.218933 & 1.243200 & 1.218400 & 1.208667 & 1.236667 & 1.249867 & 1.213867 & 1.783067 & 1.219600 & 1.910400 & 1.221467 & 1.285733 & 2.018533 \\
ESL & 0.307377 & 0.498361 & 0.311749 & 0.696175 & 0.391257 & 0.321858 & 0.300820 & 0.455738 & 0.305738 & 0.322131 & 0.310383 & 0.301913 & 0.301366 & 0.340437 & 0.298361 & 0.365301 & 0.311749 & 0.343443 & 0.313388 & 0.321311 & 0.348361 \\
LEV & 0.414667 & 0.637200 & 0.423867 & 1.023467 & 0.593600 & 0.408400 & 0.421867 & 0.416533 & 0.410133 & 0.406267 & 0.409333 & 0.410533 & 0.400800 & 0.434400 & 0.412400 & 0.512267 & 0.408667 & 0.406133 & 0.425733 & 0.401600 & 0.409467 \\
SWD & 0.449200 & 0.653733 & 0.489067 & 1.031867 & 0.581333 & 0.446533 & 0.440133 & 0.478933 & 0.445067 & 0.452000 & 0.450133 & 0.446400 & 0.446400 & 0.462800 & 0.450533 & 0.578533 & 0.451333 & 0.477733 & 0.450133 & 0.439733 & 0.475733 \\
automobile & 0.578205 & 0.659615 & 0.748718 & 0.758974 & 0.792949 & 0.503205 & 0.594231 & 0.851282 & 0.403205 & 0.544231 & 0.953205 & 0.416026 & 0.371154 & 0.348077 & 0.394872 & 0.387820 & 0.394231 & 0.392949 & 0.471795 & 0.361539 & 0.388462 \\
balance-scale & 0.148832 & 0.106794 & 0.203822 & 0.106794 & 0.106794 & 0.043737 & 0.034183 & 0.105308 & 0.001274 & 0.088535 & 0.106794 & 0.002123 & 0.031635 & 0.032484 & 0.002548 & 0.163694 & 0.167941 & 0.030573 & 0.106794 & 0.030149 & 0.030573 \\
car & 0.080401 & 0.079784 & 0.084182 & 0.080093 & 0.073225 & 0.029167 & 0.037577 & 0.116589 & 0.012654 & 0.175231 & 1.450540 & 0.012577 & 0.003626 & 0.011960 & 0.012423 & 0.046451 & 0.027006 & 0.015432 & 0.080864 & 0.007099 & 0.014352 \\
contact-lenses & 0.500000 & 0.427778 & 0.572222 & 0.411111 & 0.388889 & 0.455556 & 0.511111 & 0.483333 & 0.461111 & 0.522222 & 0.533333 & 0.483333 & 0.500000 & 0.416667 & 0.516667 & 0.516667 & 0.377778 & 0.455556 & 0.477778 & 0.522222 & 0.461111 \\
eucalyptus & 1.001449 & 1.014493 & 0.991486 & 0.998732 & 1.105435 & 0.475725 & 0.330978 & 0.575000 & 0.395109 & 0.530978 & 1.938768 & 0.403080 & 0.404529 & 0.414674 & 0.393116 & 0.400543 & 0.400543 & 0.505435 & 0.384058 & 0.409602 & 0.507246 \\
newthyroid & 0.032099 & 0.036420 & 0.032099 & 0.036420 & 0.024691 & 0.035185 & 0.033951 & 0.033333 & 0.029013 & 0.051852 & 0.027778 & 0.031482 & 0.041358 & 0.041975 & 0.033951 & 0.024692 & 0.048766 & 0.038272 & 0.031482 & 0.035185 & 0.040124 \\
pasture & 0.481481 & 0.440741 & 0.429630 & 0.466667 & 0.429630 & 0.240740 & 0.488889 & 0.370370 & 0.329629 & 0.403704 & 0.585185 & 0.333333 & 0.292592 & 0.300000 & 0.344444 & 0.340741 & 0.322222 & 0.337037 & 0.337037 & 0.296296 & 0.322222 \\
squash-stored & 0.428205 & 0.523077 & 0.474359 & 0.520513 & 0.512821 & 0.420513 & 0.625641 & 0.538462 & 0.346154 & 0.484615 & 0.812821 & 0.366667 & 0.410256 & 0.364102 & 0.382051 & 0.374359 & 0.369231 & 0.433333 & 0.376923 & 0.376923 & 0.458974 \\
squash-unstored & 0.243590 & 0.279487 & 0.243590 & 0.261538 & 0.264103 & 0.276923 & 0.356410 & 0.423077 & 0.261538 & 0.423077 & 0.825641 & 0.261538 & 0.269231 & 0.305128 & 0.271795 & 0.251282 & 0.269230 & 0.282051 & 0.317948 & 0.215384 & 0.282051 \\
tae & 0.602632 & 0.607895 & 0.664035 & 0.667544 & 0.598246 & 0.540351 & 0.861404 & 0.580702 & 0.461403 & 0.624561 & 0.628070 & 0.465789 & 0.500000 & 0.504386 & 0.469298 & 0.460526 & 0.479824 & 0.521053 & 0.579825 & 0.542982 & 0.495614 \\
winequality-red & 0.437833 & 1.500583 & 0.439667 & 1.896750 & 0.812500 & 0.439333 & 0.424833 & 0.446833 & 0.417500 & 0.432417 & 0.435083 & 0.416750 & 0.407083 & 0.365500 & 0.419417 & 0.392667 & 0.416167 & 0.419000 & 0.444750 & 0.411417 & 0.420333 \\
\bottomrule
\end{tabular}

# TABLAS LATEX

In [54]:
import pandas as pd

def bold_min_in_row(df):
    """
    Reemplaza el valor mínimo de cada fila en un DataFrame con una cadena LaTeX en negrita,
    ignorando la primera fila y la primera columna.
    
    Args:
    df (pd.DataFrame): DataFrame de entrada con la primera fila y columna como palabras y el resto como números.
    
    Returns:
    pd.DataFrame: DataFrame con los valores mínimos de cada fila reemplazados por cadenas LaTeX en negrita.
    """
    def bold_min_latex(row):
        # Ignorar la primera columna al calcular el mínimo
        numeric_values = row[1:]
        min_val = numeric_values.min()
        return [row[0]] + [f"\\textbf{{{val}}}" if val == min_val else val for val in numeric_values]
    
    # Aplicar la función a partir de la segunda fila
    df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
    return df

In [10]:

#Nos quedamos con las hojas MAE, AMAE, MMAE Y MZE
df_MAE=pd.read_excel('Metrics_2D5_std_.xlsx', sheet_name='MAE')
df_AMAE=pd.read_excel('Metrics_2D5_std_.xlsx', sheet_name='AMAE')
df_MMAE=pd.read_excel('Metrics_2D5_std_.xlsx', sheet_name='MMAE')
df_MZE=pd.read_excel('Metrics_2D5_std_.xlsx', sheet_name='MZE')

In [16]:
#nos quedamos con las columnas que nos interesan: dataset logisticat y logisticat_desb_v2
#df = df_MZE[['dataset','logisticit','logisticit_desb_v2']]
df=df_MZE
#nos quedamos con las filas correspondientes a los datasets: balance-scale, car, contact-lenses, pasture, tae y toy
#df = df.loc[df['dataset'].isin(['ERA','balance-scale','car','contact-lenses','eucalyptus','pasture','tae','toy'])]
#eliminamos las columnas de logisticat y logisticit
df = df.drop(columns=['logisticat','logisticat_desb_v2','logisticregressor'])
print(df.to_latex(index=False))

\begin{tabular}{lll}
\toprule
dataset & logisticit & logisticit_desb_v2 \\
\midrule
abalone & 0.232 ± 0.006 & 0.38 ± 0.013 \\
auto & 0.248 ± 0.032 & 0.316 ± 0.031 \\
diabetes & 0.513 ± 0.082 & 0.751 ± 0.096 \\
housing & 0.284 ± 0.024 & 0.323 ± 0.034 \\
machine & 0.141 ± 0.029 & 0.207 ± 0.041 \\
pyrim & 0.459 ± 0.083 & 0.513 ± 0.079 \\
stock & 0.305 ± 0.021 & 0.295 ± 0.021 \\
triazines & 0.607 ± 0.075 & 0.739 ± 0.048 \\
wpbc & 0.66 ± 0.035 & 0.685 ± 0.037 \\
\bottomrule
\end{tabular}

In [5]:
df_AMAE

,dataset,logisticat,logisticat_desb_v2,logisticit,logisticit_desb_v2,logisticregressor
0,ERA,1.454 ± 0.064,1.315 ± 0.102,2.486 ± 0.157,2.503 ± 0.172,1.512 ± 0.07
1,ESL,0.428 ± 0.102,0.504 ± 0.109,0.429 ± 0.105,0.631 ± 0.167,0.41 ± 0.084
2,LEV,0.64 ± 0.053,0.603 ± 0.068,0.633 ± 0.061,0.811 ± 0.121,0.594 ± 0.07
3,SWD,0.609 ± 0.028,0.549 ± 0.055,0.623 ± 0.044,0.73 ± 0.05,0.495 ± 0.049
4,automobile,0.776 ± 0.115,0.597 ± 0.106,0.901 ± 0.104,0.615 ± 0.09,0.734 ± 0.138
5,balance-scale,0.25 ± 0.149,0.104 ± 0.027,0.421 ± 0.019,0.104 ± 0.027,0.104 ± 0.027
6,car,0.219 ± 0.041,0.122 ± 0.024,0.261 ± 0.039,0.118 ± 0.025,0.075 ± 0.036
7,contact-lenses,0.581 ± 0.295,0.37 ± 0.227,0.656 ± 0.315,0.333 ± 0.202,0.306 ± 0.239
8,eucalyptus,1.055 ± 0.06,1.09 ± 0.043,1.061 ± 0.038,1.066 ± 0.045,1.142 ± 0.114
9,newthyroid,0.052 ± 0.034,0.044 ± 0.032,0.052 ± 0.034,0.044 ± 0.032,0.033 ± 0.038
10,pasture,0.485 ± 0.252,0.433 ± 0.176,0.422 ± 0.219,0.441 ± 0.234,0.437 ± 0.18
11,squash-stored,0.488 ± 0.169,0.523 ± 0.204,0.476 ± 0.184,0.514 ± 0.202,0.583 ± 0.222
12,squash-unstored,0.233 ± 0.148,0.281 ± 0.152,0.259 ± 0.175,0.272 ± 0.157,0.265 ± 0.164
13,tae,0.704 ± 0.181,0.7 ± 0.173,0.676 ± 0.092,0.673 ± 0.097,0.61 ± 0.115
14,toy,1.189 ± 0.13,1.499 ± 0.164,1.779 ± 0.205,1.627 ± 0.214,1.051 ± 0.097
15,winequality-red,1.08 ± 0.045,1.239 ± 0.144,1.072 ± 0.032,1.178 ± 0.072,0.872 ± 0.11

In [16]:
df=pd.read_csv('0.Comparativa_MAE_Propio+Review.csv')
df=bold_min_in_row(df)
print(df.to_latex(index=False))

\begin{tabular}{lrllllll}
\toprule
dataset & logisticat & logisticat_desb_v2 & logisticit & logisticit_desb_v2 & logisticregressor & POM & SVORIMLin \\
\midrule
ERA & 1.222000 & 1.449000 & 2.787000 & 2.815000 & 1.737000 & 1.218000 & 1.221000 \\
ESL & 0.308000 & 0.509000 & 0.314000 & 0.648000 & 0.392000 & \textbf{0.31} & 0.313000 \\
LEV & 0.415000 & 0.689000 & 0.424000 & 1.012000 & 0.593000 & \textbf{0.409} & 0.426000 \\
SWD & 0.449000 & 0.705000 & 0.528000 & 1.034000 & 0.580000 & \textbf{0.45} & \textbf{0.45} \\
automobile & 0.592000 & 0.653000 & 0.693000 & 0.744000 & 0.803000 & 0.953000 & \textbf{0.472} \\
balance-scale & 0.150000 & \textbf{0.107} & 0.204000 & \textbf{0.107} & \textbf{0.107} & \textbf{0.107} & \textbf{0.107} \\
car & 0.080000 & 0.080000 & 0.084000 & 0.080000 & \textbf{0.073} & 1.451000 & 0.081000 \\
contact-lenses & 0.478000 & 0.422000 & 0.567000 & 0.422000 & \textbf{0.383} & 0.533000 & 0.478000 \\
eucalyptus & 1.003000 & 1.022000 & 0.992000 & 0.999000 & 1.103000 & 1.939000 & \textbf{0.384} \\
newthyroid & 0.032000 & 0.036000 & 0.032000 & 0.036000 & \textbf{0.025} & 0.028000 & 0.031000 \\
pasture & 0.485000 & 0.433000 & 0.422000 & 0.441000 & 0.437000 & 0.585000 & \textbf{0.337} \\
squash-stored & 0.449000 & 0.521000 & 0.441000 & 0.521000 & 0.518000 & 0.813000 & \textbf{0.377} \\
squash-unstored & 0.246000 & 0.274000 & \textbf{0.244} & 0.262000 & 0.264000 & 0.826000 & 0.318000 \\
tae & 0.702000 & 0.699000 & 0.674000 & 0.671000 & 0.610000 & 0.628000 & \textbf{0.58} \\
toy & 0.998000 & 1.575000 & 1.917000 & 1.762000 & 1.154000 & 0.981000 & \textbf{0.964} \\
winequality-red & 0.439000 & 1.501000 & 0.438000 & 1.874000 & 0.810000 & \textbf{0.435} & 0.445000 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_5497/4157772143.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return [row[0]] + [f"\\textbf{{{val}}}" if val == min_val else val for val in numeric_values]
/tmp/ipykernel_5497/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.509 0.689 0.705 0.653 '\\textbf{0.107}' 0.08 0.422 1.022 0.036 0.433
 0.521 0.274 0.699 1.575 1.501]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
/tmp/ipykernel_5497/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.314 0.424 0.528 0.693 0.204 0.084 0.567 0.992 0.032 0.422 0.441
 '\\textbf{0.244}' 0.674 1.917 0.438]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
/tmp/ipykernel_5497/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.648 1.012 1.034 0.744 '\\textbf{0.107}' 0.08 0.422 0.999 0.036 0.441
 0.521 0.262 0.671 1.762 1.874]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
/tmp/ipykernel_5497/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.392 0.593 0.58 0.803 '\\textbf{0.107}' '\\textbf{0.073}'
 '\\textbf{0.383}' 1.103 '\\textbf{0.025}' 0.437 0.518 0.264 0.61 1.154
 0.81]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
/tmp/ipykernel_5497/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['\\textbf{0.31}' '\\textbf{0.409}' '\\textbf{0.45}' 0.953
 '\\textbf{0.107}' 1.451 0.533 1.939 0.028 0.585 0.813 0.826 0.628 0.981
 '\\textbf{0.435}']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
/tmp/ipykernel_5497/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.313 0.426 '\\textbf{0.45}' '\\textbf{0.472}' '\\textbf{0.107}' 0.081
 0.478 '\\textbf{0.384}' 0.031 '\\textbf{0.337}' '\\textbf{0.377}' 0.318
 '\\textbf{0.58}' '\\textbf{0.964}' 0.445]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)

In [46]:
dff=bold_min_in_row(df_AMAE)
print(dff.to_latex(index=False))

\begin{tabular}{lrlrrl}
\toprule
dataset & logisticat & logisticat_desb_v2 & logisticit & logisticit_desb_v2 & logisticregressor \\
\midrule
abalone & 0.805000 & 0.434000 & 0.851000 & 0.471000 & 0.485000 \\
auto & 0.365000 & \textbf{0.34} & 0.368000 & 0.343000 & 0.362000 \\
diabetes & 0.915000 & \textbf{0.573} & 1.061000 & 0.760000 & 0.643000 \\
housing & 0.404000 & \textbf{0.332} & 0.466000 & 0.357000 & 0.364000 \\
machine & 0.430000 & \textbf{0.332} & 0.398000 & 0.349000 & 0.487000 \\
pyrim & 0.612000 & \textbf{0.529} & 0.615000 & 0.569000 & 0.613000 \\
stock & 0.292000 & 0.268000 & 0.285000 & 0.258000 & \textbf{0.162} \\
triazines & 1.381000 & \textbf{1.09} & 1.556000 & 1.401000 & 1.118000 \\
wpbc & 1.347000 & \textbf{1.181} & 1.654000 & 1.472000 & 1.227000 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_6296/4157772143.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return [row[0]] + [f"\\textbf{{{val}}}" if val == min_val else val for val in numeric_values]
/tmp/ipykernel_6296/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['\\textbf{0.34}' '\\textbf{0.573}' '\\textbf{0.332}' '\\textbf{0.332}'
 '\\textbf{0.529}' 0.268 '\\textbf{1.09}' '\\textbf{1.181}']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
/tmp/ipykernel_6296/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.362 0.643 0.364 0.487 0.613 '\\textbf{0.162}' 1.118 1.227]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)

In [47]:
d=bold_min_in_row(df_MZE)
print(d.to_latex(index=False))

\begin{tabular}{lrllrl}
\toprule
dataset & logisticat & logisticat_desb_v2 & logisticit & logisticit_desb_v2 & logisticregressor \\
\midrule
abalone & 0.224000 & 0.416000 & 0.232000 & 0.380000 & 0.354000 \\
auto & 0.242000 & 0.312000 & \textbf{0.248} & 0.316000 & 0.333000 \\
diabetes & 0.515000 & 0.636000 & \textbf{0.513} & 0.751000 & 0.672000 \\
housing & 0.275000 & 0.335000 & \textbf{0.284} & 0.323000 & 0.340000 \\
machine & 0.143000 & 0.213000 & \textbf{0.141} & 0.207000 & 0.272000 \\
pyrim & 0.445000 & \textbf{0.459} & \textbf{0.459} & 0.513000 & 0.468000 \\
stock & 0.310000 & 0.302000 & 0.305000 & 0.295000 & \textbf{0.183} \\
triazines & 0.564000 & 0.683000 & 0.607000 & 0.739000 & \textbf{0.551} \\
wpbc & 0.669000 & 0.675000 & \textbf{0.66} & 0.685000 & 0.745000 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_6296/4157772143.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return [row[0]] + [f"\\textbf{{{val}}}" if val == min_val else val for val in numeric_values]
/tmp/ipykernel_6296/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.312 0.636 0.335 0.213 '\\textbf{0.459}' 0.302 0.683 0.675]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
/tmp/ipykernel_6296/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['\\textbf{0.248}' '\\textbf{0.513}' '\\textbf{0.284}' '\\textbf{0.141}'
 '\\textbf{0.459}' 0.305 0.607 '\\textbf{0.66}']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
/tmp/ipykernel_6296/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.333 0.672 0.34 0.272 0.468 '\\textbf{0.183}' '\\textbf{0.551}' 0.745]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)

In [50]:
amae=bold_min_in_row(df_AMAE)
print(amae.to_latex(index=False))

\begin{tabular}{lrlrrl}
\toprule
dataset & logisticat & logisticat_desb_v2 & logisticit & logisticit_desb_v2 & logisticregressor \\
\midrule
abalone & 0.805000 & 0.434000 & 0.851000 & 0.471000 & 0.485000 \\
auto & 0.365000 & \textbf{0.34} & 0.368000 & 0.343000 & 0.362000 \\
diabetes & 0.915000 & \textbf{0.573} & 1.061000 & 0.760000 & 0.643000 \\
housing & 0.404000 & \textbf{0.332} & 0.466000 & 0.357000 & 0.364000 \\
machine & 0.430000 & \textbf{0.332} & 0.398000 & 0.349000 & 0.487000 \\
pyrim & 0.612000 & \textbf{0.529} & 0.615000 & 0.569000 & 0.613000 \\
stock & 0.292000 & 0.268000 & 0.285000 & 0.258000 & \textbf{0.162} \\
triazines & 1.381000 & \textbf{1.09} & 1.556000 & 1.401000 & 1.118000 \\
wpbc & 1.347000 & \textbf{1.181} & 1.654000 & 1.472000 & 1.227000 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_6296/4157772143.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return [row[0]] + [f"\\textbf{{{val}}}" if val == min_val else val for val in numeric_values]
/tmp/ipykernel_6296/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['\\textbf{0.34}' '\\textbf{0.573}' '\\textbf{0.332}' '\\textbf{0.332}'
 '\\textbf{0.529}' 0.268 '\\textbf{1.09}' '\\textbf{1.181}']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)
/tmp/ipykernel_6296/4157772143.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.362 0.643 0.364 0.487 0.613 '\\textbf{0.162}' 1.118 1.227]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[1:, 1:] = df.iloc[1:, 1:].apply(lambda row: pd.Series(bold_min_latex(row), index=row.index), axis=1)

# otro

In [62]:
df_pom=pd.read_csv('Review/Ordinal/summary-svorimLin.csv')
df_=df_pom[['Dataset','MZEMean','MZESD']]
#seleccionamos los datasets presentes en list_datasets
df_=df_.loc[df_['Dataset'].isin(list_datasets)]
df_

            Dataset   MZEMean     MZESD
0               ERA  0.749867  0.023246
1               ESL  0.293443  0.032886
2               LEV  0.383733  0.027910
3               SWD  0.431467  0.030277
6        automobile  0.408333  0.068446
7     balance-scale  0.094480  0.018557
15              car  0.076929  0.010347
24   contact-lenses  0.361111  0.098682
25       eucalyptus  0.356522  0.022503
30       newthyroid  0.030864  0.024478
31          pasture  0.344444  0.121541
34    squash-stored  0.371795  0.132595
35  squash-unstored  0.315385  0.113108
38              tae  0.459649  0.072063
39              toy  0.730222  0.015924
40  winequality-red  0.406667  0.015148

In [63]:
import pandas as pd

# Hacemos un DataFrame en blanco con las columnas 'Dataset' y 'POM'
df_final = pd.DataFrame(columns=['Dataset', 'SvorimLin'])

# Rellenamos la columna 'Dataset' con los datasets de list_datasets y en la columna 'POM' con los valores de AMAESMean +- AMAESSTD (en texto)
for dataset in list_datasets:
    pom_value = str(round(df_.loc[df_['Dataset'] == dataset]['MZEMean'].values[0],3)) + ' ± ' + str(round(df_.loc[df_['Dataset'] == dataset]['MZESD'].values[0],3))
    new_row = pd.DataFrame({'Dataset': [dataset], 'SvorimLin': [pom_value]})
    df_final = pd.concat([df_final, new_row], ignore_index=True)

#guardamos el csv
df_final.to_csv('Review/Ordinal/svorimLin_mze.csv', index=False)
# Mostrar el DataFrame final
print(df_final)

            Dataset      SvorimLin
0               ERA   0.75 ± 0.023
1               ESL  0.293 ± 0.033
2               LEV  0.384 ± 0.028
3               SWD   0.431 ± 0.03
4        automobile  0.408 ± 0.068
5     balance-scale  0.094 ± 0.019
6               car   0.077 ± 0.01
7    contact-lenses  0.361 ± 0.099
8        eucalyptus  0.357 ± 0.023
9        newthyroid  0.031 ± 0.024
10          pasture  0.344 ± 0.122
11    squash-stored  0.372 ± 0.133
12  squash-unstored  0.315 ± 0.113
13              tae   0.46 ± 0.072
14              toy   0.73 ± 0.016
15  winequality-red  0.407 ± 0.015

In [47]:
df_propio=pd.read_excel('Metrics_2R_std_.xlsx', sheet_name='AMAE')
#lecambiamos el nombre a la columna dataset por Datasets
df_propio.rename(columns={'dataset':'Dataset'}, inplace=True)
pom=pd.read_csv('Review/Ordinal/pom_amae.csv')
svorimlin=pd.read_csv('Review/Ordinal/SvorimLin_amae.csv')

In [48]:
pom

            Dataset            POM
0               ERA  1.384 ± 0.085
1               ESL  0.442 ± 0.095
2               LEV  0.627 ± 0.054
3               SWD  0.622 ± 0.031
4        automobile    1.026 ± 0.8
5     balance-scale  0.104 ± 0.027
6               car  0.896 ± 0.271
7    contact-lenses   0.51 ± 0.286
8        eucalyptus   1.89 ± 0.238
9        newthyroid    0.05 ± 0.04
10          pasture  0.585 ± 0.204
11    squash-stored  0.815 ± 0.251
12  squash-unstored  0.791 ± 0.332
13              tae  0.629 ± 0.118
14              toy  1.213 ± 0.059
15  winequality-red   1.083 ± 0.04

In [49]:
df_propio

,Dataset,logisticat,logisticat_desb_v2,logisticit,logisticit_desb_v2,logisticregressor
0,ERA,1.454 ± 0.064,1.315 ± 0.102,2.486 ± 0.157,2.503 ± 0.172,1.512 ± 0.07
1,ESL,0.428 ± 0.102,0.504 ± 0.109,0.429 ± 0.105,0.631 ± 0.167,0.41 ± 0.084
2,LEV,0.64 ± 0.053,0.603 ± 0.068,0.633 ± 0.061,0.811 ± 0.121,0.594 ± 0.07
3,SWD,0.609 ± 0.028,0.549 ± 0.055,0.623 ± 0.044,0.73 ± 0.05,0.495 ± 0.049
4,automobile,0.776 ± 0.115,0.597 ± 0.106,0.901 ± 0.104,0.615 ± 0.09,0.734 ± 0.138
5,balance-scale,0.25 ± 0.149,0.104 ± 0.027,0.421 ± 0.019,0.104 ± 0.027,0.104 ± 0.027
6,car,0.219 ± 0.041,0.122 ± 0.024,0.261 ± 0.039,0.118 ± 0.025,0.075 ± 0.036
7,contact-lenses,0.581 ± 0.295,0.37 ± 0.227,0.656 ± 0.315,0.333 ± 0.202,0.306 ± 0.239
8,eucalyptus,1.055 ± 0.06,1.09 ± 0.043,1.061 ± 0.038,1.066 ± 0.045,1.142 ± 0.114
9,newthyroid,0.052 ± 0.034,0.044 ± 0.032,0.052 ± 0.034,0.044 ± 0.032,0.033 ± 0.038
10,pasture,0.485 ± 0.252,0.433 ± 0.176,0.422 ± 0.219,0.441 ± 0.234,0.437 ± 0.18
11,squash-stored,0.488 ± 0.169,0.523 ± 0.204,0.476 ± 0.184,0.514 ± 0.202,0.583 ± 0.222
12,squash-unstored,0.233 ± 0.148,0.281 ± 0.152,0.259 ± 0.175,0.272 ± 0.157,0.265 ± 0.164
13,tae,0.704 ± 0.181,0.7 ± 0.173,0.676 ± 0.092,0.673 ± 0.097,0.61 ± 0.115
14,toy,1.189 ± 0.13,1.499 ± 0.164,1.779 ± 0.205,1.627 ± 0.214,1.051 ± 0.097
15,winequality-red,1.08 ± 0.045,1.239 ± 0.144,1.072 ± 0.032,1.178 ± 0.072,0.872 ± 0.11

In [50]:
#unimos los df por la columna dataset
df = pd.merge(df_propio, pom, on='Dataset', how='inner')

In [51]:
df = pd.merge(df, svorimlin, on='Dataset', how='inner')

In [52]:
df

,Dataset,logisticat,logisticat_desb_v2,logisticit,logisticit_desb_v2,logisticregressor,POM,SvorimLin
0,ERA,1.454 ± 0.064,1.315 ± 0.102,2.486 ± 0.157,2.503 ± 0.172,1.512 ± 0.07,1.384 ± 0.085,1.455 ± 0.09
1,ESL,0.428 ± 0.102,0.504 ± 0.109,0.429 ± 0.105,0.631 ± 0.167,0.41 ± 0.084,0.442 ± 0.095,0.477 ± 0.103
2,LEV,0.64 ± 0.053,0.603 ± 0.068,0.633 ± 0.061,0.811 ± 0.121,0.594 ± 0.07,0.627 ± 0.054,0.632 ± 0.059
3,SWD,0.609 ± 0.028,0.549 ± 0.055,0.623 ± 0.044,0.73 ± 0.05,0.495 ± 0.049,0.622 ± 0.031,0.602 ± 0.041
4,automobile,0.776 ± 0.115,0.597 ± 0.106,0.901 ± 0.104,0.615 ± 0.09,0.734 ± 0.138,1.026 ± 0.8,0.582 ± 0.098
5,balance-scale,0.25 ± 0.149,0.104 ± 0.027,0.421 ± 0.019,0.104 ± 0.027,0.104 ± 0.027,0.104 ± 0.027,0.104 ± 0.027
6,car,0.219 ± 0.041,0.122 ± 0.024,0.261 ± 0.039,0.118 ± 0.025,0.075 ± 0.036,0.896 ± 0.271,0.187 ± 0.045
7,contact-lenses,0.581 ± 0.295,0.37 ± 0.227,0.656 ± 0.315,0.333 ± 0.202,0.306 ± 0.239,0.51 ± 0.286,0.5 ± 0.265
8,eucalyptus,1.055 ± 0.06,1.09 ± 0.043,1.061 ± 0.038,1.066 ± 0.045,1.142 ± 0.114,1.89 ± 0.238,0.409 ± 0.035
9,newthyroid,0.052 ± 0.034,0.044 ± 0.032,0.052 ± 0.034,0.044 ± 0.032,0.033 ± 0.038,0.05 ± 0.04,0.055 ± 0.05
10,pasture,0.485 ± 0.252,0.433 ± 0.176,0.422 ± 0.219,0.441 ± 0.234,0.437 ± 0.18,0.585 ± 0.204,0.337 ± 0.115
11,squash-stored,0.488 ± 0.169,0.523 ± 0.204,0.476 ± 0.184,0.514 ± 0.202,0.583 ± 0.222,0.815 ± 0.251,0.413 ± 0.157
12,squash-unstored,0.233 ± 0.148,0.281 ± 0.152,0.259 ± 0.175,0.272 ± 0.157,0.265 ± 0.164,0.791 ± 0.332,0.406 ± 0.163
13,tae,0.704 ± 0.181,0.7 ± 0.173,0.676 ± 0.092,0.673 ± 0.097,0.61 ± 0.115,0.629 ± 0.118,0.548 ± 0.079
14,toy,1.189 ± 0.13,1.499 ± 0.164,1.779 ± 0.205,1.627 ± 0.214,1.051 ± 0.097,1.213 ± 0.059,1.203 ± 0.04
15,winequality-red,1.08 ± 0.045,1.239 ± 0.144,1.072 ± 0.032,1.178 ± 0.072,0.872 ± 0.11,1.083 ± 0.04,1.089 ± 0.041

In [55]:
df=bold_min_in_row(df)
print(df.to_latex(index=False))

/tmp/ipykernel_6371/4157772143.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return [row[0]] + [f"\\textbf{{{val}}}" if val == min_val else val for val in numeric_values]

\begin{tabular}{llllllll}
\toprule
Dataset & logisticat & logisticat_desb_v2 & logisticit & logisticit_desb_v2 & logisticregressor & POM & SvorimLin \\
\midrule
ERA & 1.454 ± 0.064 & 1.315 ± 0.102 & 2.486 ± 0.157 & 2.503 ± 0.172 & 1.512 ± 0.07 & 1.384 ± 0.085 & 1.455 ± 0.09 \\
ESL & 0.428 ± 0.102 & 0.504 ± 0.109 & 0.429 ± 0.105 & 0.631 ± 0.167 & \textbf{0.41 ± 0.084} & 0.442 ± 0.095 & 0.477 ± 0.103 \\
LEV & 0.64 ± 0.053 & 0.603 ± 0.068 & 0.633 ± 0.061 & 0.811 ± 0.121 & \textbf{0.594 ± 0.07} & 0.627 ± 0.054 & 0.632 ± 0.059 \\
SWD & 0.609 ± 0.028 & 0.549 ± 0.055 & 0.623 ± 0.044 & 0.73 ± 0.05 & \textbf{0.495 ± 0.049} & 0.622 ± 0.031 & 0.602 ± 0.041 \\
automobile & 0.776 ± 0.115 & 0.597 ± 0.106 & 0.901 ± 0.104 & 0.615 ± 0.09 & 0.734 ± 0.138 & 1.026 ± 0.8 & \textbf{0.582 ± 0.098} \\
balance-scale & 0.25 ± 0.149 & \textbf{0.104 ± 0.027} & 0.421 ± 0.019 & \textbf{0.104 ± 0.027} & \textbf{0.104 ± 0.027} & \textbf{0.104 ± 0.027} & \textbf{0.104 ± 0.027} \\
car & 0.219 ± 0.041 & 0.122 ± 0.024 & 0.261 ± 0.039 & 0.118 ± 0.025 & \textbf{0.075 ± 0.036} & 0.896 ± 0.271 & 0.187 ± 0.045 \\
contact-lenses & 0.581 ± 0.295 & 0.37 ± 0.227 & 0.656 ± 0.315 & 0.333 ± 0.202 & \textbf{0.306 ± 0.239} & 0.51 ± 0.286 & 0.5 ± 0.265 \\
eucalyptus & 1.055 ± 0.06 & 1.09 ± 0.043 & 1.061 ± 0.038 & 1.066 ± 0.045 & 1.142 ± 0.114 & 1.89 ± 0.238 & \textbf{0.409 ± 0.035} \\
newthyroid & 0.052 ± 0.034 & 0.044 ± 0.032 & 0.052 ± 0.034 & 0.044 ± 0.032 & \textbf{0.033 ± 0.038} & 0.05 ± 0.04 & 0.055 ± 0.05 \\
pasture & 0.485 ± 0.252 & 0.433 ± 0.176 & 0.422 ± 0.219 & 0.441 ± 0.234 & 0.437 ± 0.18 & 0.585 ± 0.204 & \textbf{0.337 ± 0.115} \\
squash-stored & 0.488 ± 0.169 & 0.523 ± 0.204 & 0.476 ± 0.184 & 0.514 ± 0.202 & 0.583 ± 0.222 & 0.815 ± 0.251 & \textbf{0.413 ± 0.157} \\
squash-unstored & 0.233 ± 0.148 & 0.281 ± 0.152 & \textbf{0.259 ± 0.175} & 0.272 ± 0.157 & 0.265 ± 0.164 & 0.791 ± 0.332 & 0.406 ± 0.163 \\
tae & 0.704 ± 0.181 & 0.7 ± 0.173 & 0.676 ± 0.092 & 0.673 ± 0.097 & 0.61 ± 0.115 & 0.629 ± 0.118 & \textbf{0.548 ± 0.079} \\
toy & 1.189 ± 0.13 & 1.499 ± 0.164 & 1.779 ± 0.205 & 1.627 ± 0.214 & \textbf{1.051 ± 0.097} & 1.213 ± 0.059 & 1.203 ± 0.04 \\
winequality-red & 1.08 ± 0.045 & 1.239 ± 0.144 & 1.072 ± 0.032 & 1.178 ± 0.072 & \textbf{0.872 ± 0.11} & 1.083 ± 0.04 & 1.089 ± 0.041 \\
\bottomrule
\end{tabular}